Followup #8
Remnants-of-Remnants/DirectX3D pull request #118
Opened 2024-05-10 17:09 UTC by superozing

2024-05-11 00:02 UTC, jeontigger requested changes
데칼은 렌더컴포넌트니까 상위 클래스의 세이브 로드를 호출해야할듯?

2024-05-11 02:42 UTC, skdy1201 approved these changes

2024-05-12 08:06 UTC, zkzkzkzkzkzz approved these changes

2024-05-12 17:27 UTC, oljindudol approved these changes

2024-05-12 22:59 UTC, jeontigger approved these changes

2024-05-13 00:48 UTC, merged