Feat/#106 logging system
Remnants-of-Remnants/DirectX3D pull request #128
Opened 2024-05-15 22:57 UTC by skdy1201

2024-05-16 04:08 UTC, jeontigger requested changes
1. logmgr 글로벌에서 뺀거 같은데 그 뒤로 호출하는곳에서 include안해서 빌드 안됨
2. 로그 ui와 메시지 ui를 나눈 이유를 모르겠음
3. 로그 창 사이즈가 동적으로 변경되지 않음
![image](https://github.com/Remnants-of-Remnants/DirectX3D/assets/20323844/41c112cb-12af-49ba-a827-284c26e87f74)
4. Log 탭도 있는데 굳이 메시지 박스 최상단에 있는 Log는 없어도 될듯?

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/LogUI.h
> +    char m_LogTextFilter[255];
코딩 컨벤션에 맞춰서 m_arrLog~~ 로 이름짓길 바람

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +    ImVec4 Gray = ImVec4(0.3f, 0.3f, 0.3f, 1.0f);
렌더 업데이트에서 할 건 아닌듯

2024-05-16 04:08 UTC, jeontigger commented on Project/Engine/CLogMgr.cpp
> +	strLogSavepath += L"\\Log.txt";
로그 파일 위치 변경 필요

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +
푸시 팝 푸시 팝 -> 푸시 팝 으로 변경하면 좋을듯
```suggestion
    ImGui::PushStyleColor(ImGuiCol_Button, Gray); // 기본 배경색
    ImGui::PushStyleColor(ImGuiCol_ButtonHovered, Red); // 호버 배경색도 기본 배경색과 동일하게 설정
    ImGui::PushStyleColor(ImGuiCol_ButtonActive, Red);
    if (ImGui::Button("CopyLog"))
    {
        CLogMgr::GetInst()->CopyLog();
    }

    ImGui::SameLine();


    // 삭제 버튼
    if (ImGui::Button("DeleteLog"))
    {
        CLogMgr::GetInst()->ClearLog();
    }
    ImGui::PopStyleColor(3);

```

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +    }
이것들도 이프문에 들어가는 조건이 체크박스가 눌렸을 때이니까 의도한대로 하기 위해서는 각 요소가 true일 경우까지 체크해야 함

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/MessageUI.h
> +    string         m_charLogMsgFilter;
왜 m_char?

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/MessageUI.cpp
> +}
필히 수정 필요 -> 파라미터, 리턴 변경으로 호출부도 변경 필요할 듯 싶고, 애초에 함수화가 필요 없어보임
```suggestion
bool MessageUI::CheckSearchDisplay(const string& str)
{
    return str.find(m_charLogMsgFilter) == string::npos ? false : true;
}
```

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/MessageUI.cpp
> +}
내용은 로그레벨 자체를 비트마스크로 설정해서 변경하는게 좋을듯
애초에 무슨 동작을 하는 함수인지 잘 모르겠음
```suggestion
bool MessageUI::CheckColorDispaly(LOG_LEVEL _level)
{
    return m_iLoglvMask & _level ? true : false;
}
```

2024-05-16 04:08 UTC, jeontigger commented on Project/Client/MessageUI.h
> +    ImVec2          m_MaxTableSize;
로그 ui와 messageUI를 나누지 않았으면 필요 없어지는 것들 + 이중관리

2024-05-16 04:08 UTC, jeontigger commented on Project/Engine/CLogMgr.h
> +    vector<tLog> GetLogvec() { return m_vecLog; }
너무 값이 비싸서 &로 리턴해야할듯

2024-05-16 04:08 UTC, jeontigger commented on Project/Engine/CLogMgr.cpp
> +	string time = TagOpen + std::to_string(Log.m_fMin) + TagTimedevide + std::to_string(Log.m_fsec) + TagClose;
뭐지?? 타임매니저 냅두고 왜

2024-05-16 04:08 UTC, jeontigger commented on Project/Engine/CLogMgr.cpp
> +}
그냥 m_vecLog.clear()로는 문제 있나?

2024-05-16 04:08 UTC, jeontigger commented on Project/Engine/struct.h
> +	int		m_fsec;
int 인데 m_f이고, min이랑 sec을 구분하지 말고 그냥 누적된 float time 값만 넣고 출력하는쪽에서 계산해주면 될듯

2024-05-16 08:53 UTC, zkzkzkzkzkzz approved these changes

2024-05-20 06:12 UTC, jeontigger requested changes
수정하고 언급 한번만 부탁함

2024-05-20 06:12 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +}
이거 함수명이 Get이어야 하는거 아닌가?
```suggestion
ImVec4 LogUI::SetLogColor(tLog Log)
{
    ImVec4 Color;
    switch (Log.m_LogLv)
    {
    case Log_Level::INFO:
        return  m_LogColor[(UINT)Log_Level::INFO];
        break;
    case Log_Level::WARN:
        return m_LogColor[(UINT)Log_Level::WARN];
        break;
    case Log_Level::ERR:
        return m_LogColor[(UINT)Log_Level::ERR];
        break;
    case Log_Level::END:
        break;
    default:
        break;
    }

    return Color;
}
```

2024-05-20 06:12 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +    }
다음번엔 이런식으로 바꾸는게 더 좋을듯!

```suggestion
    if (m_LoglvCheckBox[0])
    {
        m_iLoglvMask |= LOG_LEVEL::INFO;
        m_iLoglvMask |= LOG_LEVEL::WARN;
        m_iLoglvMask |= LOG_LEVEL::ERROR;
    }
```

2024-05-20 06:12 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +        m_iLoglvMask &= 4;
의미없는 코드?

2024-05-20 06:12 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +{
애초에 여기 파라미터가 LOG_LEVEL로 들어오면 더 좋을듯?

2024-05-20 06:12 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +        m_iLogTimeMask &= 4;
아까랑 같은 ???

2024-05-20 06:12 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +    }
인수가 잘못된듯

```suggestion
        if (m_LoglvCheckBox[1])
            m_LoglvCheckBox[0] = false;
    }
    ImGui::SameLine();

    if (ImGui::Checkbox("Warn", &m_LoglvCheckBox[2]))
    {
        if (m_LoglvCheckBox[2])
            m_LoglvCheckBox[0] = false;
    }

    ImGui::SameLine();

    if (ImGui::Checkbox("Error", &m_LoglvCheckBox[3]))
    {
        if (m_LoglvCheckBox[3])
            m_LoglvCheckBox[0] = false;
    }
```

2024-05-20 06:12 UTC, jeontigger commented on Project/Client/LogUI.cpp
> +    }
이 또한...
내 설명을 이해 못하고 작성한건가?
```suggestion
        if (m_LogTimePrint[1])
            m_LogTimePrint[0] = false;
    }
    ImGui::SameLine();

    if (ImGui::Checkbox("Min", &m_LogTimePrint[2]))
    {
        if (m_LogTimePrint[2])
            m_LogTimePrint[0] = false;
    }
    ImGui::SameLine();

    if (ImGui::Checkbox("Hour", &m_LogTimePrint[3]))
    {
        if (m_LogTimePrint[3])
            m_LogTimePrint[0] = false;
    }
```

2024-05-20 12:59 UTC, jeontigger approved these changes

2024-05-21 11:40 UTC, merged