Refactor / #109 두 개 이상의 렌더 컴포넌트 추가 방지
Remnants-of-Remnants/DirectX3D pull request #130
Opened 2024-05-16 00:21 UTC by zkzkzkzkzkzz

2024-05-16 04:20 UTC, jeontigger requested changes

2024-05-16 04:20 UTC, jeontigger commented on Project/Client/Inspector.cpp
> +	}
이렇게 enum비교하는게 지금보단 유지보수에 유리해보이고, 그걸 넘어서 isRendercomponent(type) 같은 함수가 있으면 좋을듯?

```suggestion
	if (COMPONENT_TYPE::MESHRENDER <= _type && _type < COMPONENT_TYPE::END )
	{
		if (nullptr != m_TargetObject->GetRenderComponent())
		{
			MessageBoxA(nullptr, "Already contains the other render component", "Can't add more than one render component!", MB_OK);
			return;
		}
	}
```

2024-05-16 04:20 UTC, jeontigger commented on Project/Client/UI.cpp
> +	COMPONENT_TYPE Type = dynamic_cast<ComponentUI*>(_SelectedHeader)->GetType();
이건 좀 위험한듯
다이나믹 캐스트를 하고나서 if(null) 검사를 하고 gettype을 해야하는거 아닌가?
null이면 얼리 리턴 필요해보임

2024-05-16 12:38 UTC, superozing approved these changes

2024-05-16 14:27 UTC, zkzkzkzkzkzz commented on Project/Client/Inspector.cpp
> +	}
isRenderComponent함수가 들어갈 위치?에 대한 고민이 좀 생김

2024-05-20 00:44 UTC, jeontigger approved these changes

2024-05-20 00:48 UTC, merged