#8 지형에 가중치 적용 / 가중치 구조화 버퍼 device에서 생성(ror)
Remnants-of-Remnants/DirectX3D pull request #147
Opened 2024-05-28 08:23 UTC by skdy1201

2024-05-28 13:42 UTC, zkzkzkzkzkzz approved these changes

2024-05-28 23:18 UTC, oljindudol approved these changes

2024-05-29 05:20 UTC, jeontigger requested changes

2024-05-29 05:20 UTC, jeontigger commented on Project/Engine/CDevice.cpp
> +}
light, cross, weightmap 모두 묶어서 arrCB처럼 arrSB로 관리하면서 CreateStructuredBuffer 함수 하나로 해결하면 좋을듯

2024-05-29 05:20 UTC, jeontigger commented on Project/Engine/CLandScape_Init.cpp
> +	}
이건 create할게 아니라 get으로 받아와야함

2024-05-29 09:14 UTC, jeontigger approved these changes

2024-05-29 09:14 UTC, merged